name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Clone the Hugging Face Space repository
          git clone https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/ppe-detection hf-space
          
          # Copy files to HF Space (excluding .git and unnecessary files)
          rsync -av --exclude='.git' \
                    --exclude='notebooks/' \
                    --exclude='models/' \
                    --exclude='trainning results/' \
                    --exclude='data.yaml' \
                    --exclude='*.ipynb' \
                    --exclude='DEPLOYMENT_GUIDE.md' \
                    --exclude='PROJECT_SUMMARY.md' \
                    --exclude='USAGE_EXAMPLES.md' \
                    --exclude='test_local.py' \
                    --exclude='.github/' \
                    ./ hf-space/
          
          # Navigate to HF Space directory
          cd hf-space
          
          # Check if there are changes
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Auto-deploy from GitHub: ${{ github.sha }}"
            git push
            echo "✅ Successfully deployed to Hugging Face Spaces!"
          else
            echo "ℹ️ No changes to deploy"
          fi
